NameError = Exception('INVALID_NAME : Enter appropriate name')
RollNoError = Exception('INVALID_ROLL_NO : Enter valid Roll Number')   
EmailError = Exception('INVALID_EMAIL : Enter valid e-mail address')   
AddressError = Exception('CHAR_LIMIT_EXCEED : No. of characters in \'Address\' should be between 1-180')
AboutMeError = Exception('CHAR_LIMIT_EXCEED : \'About me\' should have less than 500 characters')
DeptError = Exception('INVALID_DEPT : Enter a valid department')
ExistsError = Exception('ROLL_NO_EXISTS : Roll number provided already exists')
NotFoundError = Exception('DOES_NOT_EXIST : Requested Roll Number does not exist')
