NameError = Exception('Enter appropriate name')
RollNoError = Exception('Enter valid Roll Number')   
EmailError = Exception('Enter valid e-mail address')   
AddressError = Exception('No. of characters in \'Address\' should be between 1-180')
AboutMeError = Exception('\'About me\' should have less than 500 characters')
DeptError = Exception('Enter a valid department')
ExistsError = Exception('Roll number provided already exists')
NotFoundError = Exception('Requested Roll Number does not exist')
